#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/css/style.css"/>
#+OPTIONS: toc:nil num:nil  html-style:nil
#+TITLE: About Me
#+DATE: <2021-07-12 Mon>

Hello, I'm Veera. I study computer science at UMass Amherst. I'm passionate about compilers, programming languages and operating systems. I spend most of my time working on projects that would improve my computing experience. All my projects are open source and can be found on my profile linked above. I also enjoy configuring and using Emacs for a number of day-to-day tasks. 

I love running long distances and have participated in several marathons since 2012. I try to run around five miles everyday even during the cold winters of New England. Over the years, running has become my everyday therapy.

I also play Table Tennis competitively and have been trained professionally for the past ten years. I started as a passive player and have grown to develop a strong offensive game. Nowadays, even though the pandemic has put an end my Table Tennis career, I practice occasionally to stay in touch with the sport. 

If you want to reach out, feel free to contact me via email. 

